"use client";
import { Inter } from "next/font/google";
// import "./globals.css";
import Sidebar from "@/components/sidebar/Sidebar";
import Topbar from "@/components/topbar/Topbar";
import React, { createContext, useContext, useEffect, useState } from "react";
import { styled, useTheme } from "@mui/material/styles";
import Box from "@mui/material/Box";
import MuiDrawer from "@mui/material/Drawer";
import MuiAppBar from "@mui/material/AppBar";
import Toolbar from "@mui/material/Toolbar";
import List from "@mui/material/List";
import CssBaseline from "@mui/material/CssBaseline";
import Typography from "@mui/material/Typography";
import Divider from "@mui/material/Divider";
import IconButton from "@mui/material/IconButton";
import MenuIcon from "@mui/icons-material/Menu";
import ChevronLeftIcon from "@mui/icons-material/ChevronLeft";
import ChevronRightIcon from "@mui/icons-material/ChevronRight";
import ListItem from "@mui/material/ListItem";
import ListItemButton from "@mui/material/ListItemButton";
import ListItemIcon from "@mui/material/ListItemIcon";
import ListItemText from "@mui/material/ListItemText";
import InboxIcon from "@mui/icons-material/MoveToInbox";
import MailIcon from "@mui/icons-material/Mail";
import { Avatar, Badge, Button, Link, Tooltip } from "@mui/material";
import Menu from "@mui/material/Menu";
import MenuItem from "@mui/material/MenuItem";
import NotificationsIcon from "@mui/icons-material/Notifications";
import axios from "axios";
// import { useRouter } from "next/navigation";
const SelectedPageContext = createContext();
const inter = Inter({ subsets: ["latin"] });
import Cookies from "js-cookie";
import { usePathname } from "next/navigation";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
const category = {
  NEWSKY: "home",
  "Sản xuất": "produce",
  "Kinh doanh": "business",
  Kho: "storage",
  "Vật tư": "products",
  "Mua hàng": "purchase",
  "Kế toán": "accountancy",
  "Nhân sự": "humanResources",
};
const settings = ["Thông tin", "Đổi mật khẩu", "Đăng xuất"];
const drawerWidth = 270;

const getCategory = async () => {
  try {
    const token = Cookies.get("token");
    const config = {
      Headers: { Authorization: `Bearer ${token}` },
    }; // Add your axios configuration here if needed
    const verifyToken = await axios.get(
      process.env.NEXT_PUBLIC_DB_HOST + "/product-service/category",
      config
    );
    // Handle successful token verification
    return verifyToken.data; // Return data if needed
  } catch (error) {
    console.error("Get productCategory failed:", error);
    throw error; // Rethrow the error for handling elsewhere if needed
  }
};

const openedMixin = (theme) => ({
  width: drawerWidth,
  transition: theme.transitions.create("width", {
    easing: theme.transitions.easing.sharp,
    duration: theme.transitions.duration.enteringScreen,
  }),
  overflowX: "hidden",
});

const closedMixin = (theme) => ({
  transition: theme.transitions.create("width", {
    easing: theme.transitions.easing.sharp,
    duration: theme.transitions.duration.leavingScreen,
  }),
  overflowX: "hidden",
  width: `calc(${theme.spacing(7)} + 1px)`,
  [theme.breakpoints.up("sm")]: {
    width: `calc(${theme.spacing(8)} + 1px)`,
  },
});

const DrawerHeader = styled("div")(({ theme }) => ({
  display: "flex",
  alignItems: "center",
  justifyContent: "flex-end",
  padding: theme.spacing(0, 1),
  // necessary for content to be below app bar
  ...theme.mixins.toolbar,
}));

const AppBar = styled(MuiAppBar, {
  shouldForwardProp: (prop) => prop !== "open",
})(({ theme, open }) => ({
  zIndex: theme.zIndex.drawer + 1,
  transition: theme.transitions.create(["width", "margin"], {
    easing: theme.transitions.easing.sharp,
    duration: theme.transitions.duration.leavingScreen,
  }),
  ...(open && {
    marginLeft: drawerWidth,
    width: `calc(100% - ${drawerWidth}px)`,
    transition: theme.transitions.create(["width", "margin"], {
      easing: theme.transitions.easing.sharp,
      duration: theme.transitions.duration.enteringScreen,
    }),
  }),
}));

const Drawer = styled(MuiDrawer, {
  shouldForwardProp: (prop) => prop !== "open",
})(({ theme, open }) => ({
  width: drawerWidth,
  flexShrink: 0,
  whiteSpace: "nowrap",
  boxSizing: "border-box",
  ...(open && {
    ...openedMixin(theme),
    "& .MuiDrawer-paper": openedMixin(theme),
  }),
  ...(!open && {
    ...closedMixin(theme),
    "& .MuiDrawer-paper": closedMixin(theme),
  }),
}));

export default function regularLayout({ children }) {
  const [categoriesChild, setcategoriesChild] = useState(null);
  const [anchorElUser, setAnchorElUser] = React.useState(null);
  const theme = useTheme();
  const [open, setOpen] = React.useState(true);

  const handleDrawerOpen = () => {
    setOpen(true);
  };

  const handleDrawerClose = () => {
    setOpen(false);
  };

  const handleCateClick = (key) => {
    const value = category[key];
    window.location.href = "/" + value;
  };
  const handleOpenUserMenu = (event) => {
    setAnchorElUser(event.currentTarget);
  };
  const handleCloseUserMenu = () => {
    setAnchorElUser(null);
  };
  useEffect(() => {
    //setcategoriesChild(getCategory());
    setcategoriesChild([
      {
        catName: "Vật tư",
        isChildOf: null,
        id: "7420d961-1f30-4087-8507-1133e3a79766",
      },
      {
        catName: "Danh mục tạm nhập",
        isChildOf: "44343f7f-7a6a-49b0-9787-87d2217ed289",
        id: "cf19698b-d6fd-4271-8150-25d3d280354a",
      },
      {
        catName: "Phân loại sản phẩm",
        isChildOf: "7420d961-1f30-4087-8507-1133e3a79766",
        id: "9cf6a000-4aa9-48f1-95ff-2d3fad910f4b",
      },
      {
        catName: "Danh mục đơn vị tính",
        isChildOf: "7420d961-1f30-4087-8507-1133e3a79766",
        id: "16135804-40a0-4f80-b5cd-48157f5b9a5c",
      },
      {
        catName: "Tồn 01 sản phẩm ở 01 kho",
        isChildOf: "44343f7f-7a6a-49b0-9787-87d2217ed289",
        id: "acdb4085-2568-49f2-9fe9-6a2e96157490",
      },
      {
        catName: "Danh mục xuất kho hàng hóa",
        isChildOf: "44343f7f-7a6a-49b0-9787-87d2217ed289",
        id: "2698403c-de40-43c1-a905-746c008edba0",
      },
      {
        catName: "Kho",
        isChildOf: null,
        id: "44343f7f-7a6a-49b0-9787-87d2217ed289",
      },
      {
        catName: "Thuộc tính sản phẩm",
        isChildOf: "7420d961-1f30-4087-8507-1133e3a79766",
        id: "0b1b85ea-de67-48ee-893b-b44a6370de58",
      },
      {
        catName: "Danh mục nhập kho hàng hóa",
        isChildOf: "44343f7f-7a6a-49b0-9787-87d2217ed289",
        id: "53257929-964c-407b-a6ff-cc34ca6a56fb",
      },
      {
        catName: "Danh mục Class",
        isChildOf: "7420d961-1f30-4087-8507-1133e3a79766",
        id: "854ee90b-b7e2-4b45-85c3-ce9f39e05c9f",
      },
      {
        catName: "Giá hạch toán",
        isChildOf: "7420d961-1f30-4087-8507-1133e3a79766",
        id: "63a09977-3ccf-4916-ba70-e8a585f91c77",
      },
    ]);
  }, []); // Empty dependency array ensures this effect runs only once
  //Xây dựng sidebar category
  const pathname = usePathname();
  let pathname1 = pathname.split("/");
  let pathSplit = pathname1[1];
  console.log(pathSplit);
  function getKeyByValue(object, value) {
    return Object.keys(object).find((key) => object[key] === value);
  }
  function getChildCategories(categoryName, data) {
    const category = data?.find((item) => item.catName === categoryName);

    if (!category) {
      return []; // Category not found
    }

    const children = data.filter((item) => item.isChildOf === category.id);
    let result = [...children];

    // children.forEach((child) => {
    //   const subChildren = getChildCategories(child.catName, data);
    //   result = [...result, ...subChildren];
    // });

    return result;
  }

  const categoriesAfterFilter = getChildCategories(
    getKeyByValue(category, pathSplit),
    categoriesChild
  );

  return (
    <html lang="en">
      <body className={inter.className}>
        <Box sx={{ display: "flex" }}>
          <CssBaseline />
          <AppBar position="fixed" open={open}>
            <Toolbar>
              <IconButton
                color="inherit"
                aria-label="open drawer"
                onClick={handleDrawerOpen}
                edge="start"
                sx={{
                  marginRight: 5,
                  ...(open && { display: "none" }),
                }}
              >
                <MenuIcon />
              </IconButton>
              <Button
                key={"home"}
                onClick={() => handleCateClick("NEWSKY")}
                sx={{
                  fontSize: 24,
                  color: "white",
                  display: "block",
                  fontWeight: 700,
                }}
              >
                NEWSKY
              </Button>
              <Box
                sx={{
                  flexGrow: 1,
                  display: { xs: "none", md: "flex" },
                  mx: 4,
                }}
              >
                {Object.keys(category)
                  .slice(1)
                  .map((key) => (
                    <Button
                      key={key}
                      onClick={() => handleCateClick(key)}
                      sx={{
                        my: 2,
                        color: "white",
                        display: "block",
                        fontWeight: 700,
                        letterSpacing: -0.5,
                        mx: 1,
                      }}
                    >
                      {key}
                    </Button>
                  ))}
              </Box>
              <Badge
                badgeContent={4}
                color="success"
                style={{ marginRight: 20 }}
              >
                <NotificationsIcon style={{ color: "white" }} />
              </Badge>
              <Box sx={{ flexGrow: 0 }}>
                <Tooltip title="Open settings">
                  <IconButton onClick={handleOpenUserMenu} sx={{ p: 0 }}>
                    <Avatar alt="Remy Sharp" src="" />
                  </IconButton>
                </Tooltip>
                <Menu
                  sx={{ mt: "45px" }}
                  id="menu-appbar"
                  anchorEl={anchorElUser}
                  anchorOrigin={{
                    vertical: "top",
                    horizontal: "right",
                  }}
                  keepMounted
                  transformOrigin={{
                    vertical: "top",
                    horizontal: "right",
                  }}
                  open={Boolean(anchorElUser)}
                  onClose={handleCloseUserMenu}
                >
                  {settings.map((setting) => (
                    <MenuItem key={setting} onClick={handleCloseUserMenu}>
                      <Typography textAlign="center">{setting}</Typography>
                    </MenuItem>
                  ))}
                </Menu>
              </Box>
            </Toolbar>
          </AppBar>
          <Drawer variant="permanent" open={open}>
            <DrawerHeader>
              <IconButton onClick={handleDrawerClose}>
                {theme.direction === "rtl" ? (
                  <ChevronRightIcon />
                ) : (
                  <ChevronLeftIcon />
                )}
              </IconButton>
            </DrawerHeader>
            <Divider />
            <List>
              {categoriesAfterFilter.map((text, index) => (
                <ListItem
                  key={text.catName}
                  disablePadding
                  sx={{ display: "block" }}
                >
                  <ListItemButton
                    sx={{
                      minHeight: 48,
                      justifyContent: open ? "initial" : "center",
                      px: 2.5,
                    }}
                  >
                    <ListItemIcon
                      sx={{
                        minWidth: 0,
                        mr: open ? 3 : "auto",
                        justifyContent: "center",
                      }}
                    >
                      {index % 2 === 0 ? <InboxIcon /> : <MailIcon />}
                    </ListItemIcon>
                    <ListItemText
                      primary={text.catName}
                      sx={{ opacity: open ? 1 : 0 }}
                    />
                  </ListItemButton>
                </ListItem>
              ))}
            </List>
            <Divider />
            {/* <List>
              {["All mail", "Trash", "Spam"].map((text, index) => (
                <ListItem key={text} disablePadding sx={{ display: "block" }}>
                  <ListItemButton
                    sx={{
                      minHeight: 48,
                      justifyContent: open ? "initial" : "center",
                      px: 2.5,
                    }}
                  >
                    <ListItemIcon
                      sx={{
                        minWidth: 0,
                        mr: open ? 3 : "auto",
                        justifyContent: "center",
                      }}
                    >
                      {index % 2 === 0 ? <InboxIcon /> : <MailIcon />}
                    </ListItemIcon>
                    <ListItemText
                      primary={text}
                      sx={{ opacity: open ? 1 : 0 }}
                    />
                  </ListItemButton>
                </ListItem>
              ))}
            </List> */}
          </Drawer>
          <Box component="main" sx={{ flexGrow: 1, p: 3 }}>
            <DrawerHeader />
            {children}
          </Box>
        </Box>
      </body>
    </html>
  );
}
export const useSelectedPage = () => useContext(SelectedPageContext);
